name: PACT test and publish

on:
  workflow_call:
    inputs:
      java_version:
        required: false
        type: string
        default: 21
      java_distribution:
        required: false
        type: string
        default: temurin
      pact_test_task:
        required: false
        type: string
      provider_name:
        required: true
        type: string
    secrets:
      gh_token:
        required: true
      pact_broker_url:
        required: false
      pact_broker_username:
        required: false
      pact_broker_password:
        required: false

permissions:
  contents: write
  packages: write

jobs:

  pact-test-and-publish:
    if: ${{ inputs.pact_test_task != '' && github.actor != 'dependabot[bot]' }}
    name: Pact tests
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.gh_token }}
      GIT_SHA: ${{ github.sha }}
      GIT_BRANCH: ${{ github.ref_name }}
      PACT_BROKER_URL: ${{ secrets.pact_broker_url }}
      PACT_BROKER_USERNAME: ${{ secrets.pact_broker_username }}
      PACT_BROKER_PASSWORD: ${{ secrets.pact_broker_password }}
    steps:
      - name: Get app token
        if: ${{ env.GITHUB_APP_ID != '' && env.GITHUB_APP_PRIVATE_KEY != '' }}
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ secrets.github_app_id }}
          application_private_key: ${{ secrets.github_app_private_key }}
          organization: ${{ secrets.github_app_organisation }}
      - uses: actions/checkout@v5
        if: ${{ inputs.create_tag != 'true' }}
      - uses: actions/checkout@v5
        if: ${{ inputs.create_tag == 'true' }}
        with:
          ref: ${{ inputs.override_tagged_branch }}
          token: ${{ steps.get_workflow_token.outputs.token || env.GITHUB_TOKEN }}
      - name: Set up JDK ${{ inputs.java_version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java_version }}
          distribution: ${{ inputs.java_distribution }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run pact test
        id: run_pacts
        env:
          PACT_PUBLISH: true
          PACT_BROKER_USERNAME: ${{ secrets.PACT_BROKER_USERNAME }}
          PACT_BROKER_PASSWORD: ${{ secrets.PACT_BROKER_PASSWORD }}
        run: ./gradlew ${{ inputs.pact_test_task }}

      - name: Can I merge?
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          docker run --rm \
            -e PACT_BROKER_BASE_URL=${{ secrets.PACT_BROKER_URL }} \
            -e PACT_BROKER_USERNAME=${{ secrets.PACT_BROKER_USERNAME }} \
            -e PACT_BROKER_PASSWORD=${{ secrets.PACT_BROKER_PASSWORD }} \
            pactfoundation/pact-cli:latest \
            pact-broker can-i-deploy \
            --pacticipant ${{ inputs.provider_name }} \
            --branch ${{ github.ref_name }}

      - name: Publish failed results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-problems-report
          path: build/reports/problems/
